const questions = [
	[
		`Where is Captain America from?`,
		"Queens",
		"Brooklyn",
		"Manhattan",
		"New York",
		`Brooklyn`,
	],
	[
		`Where is Spiderman from?`,
		"Queens",
		"Brooklyn",
		"Manhattan",
		"New York",
		`Queens`,
	],
	[
		`Where was Bruce Banner hidden as a doctor?`,
		"Manhattan",
		"Canada",
		"India, Kolkata",
		"India, Mumbai",
		`India, Kolkata`,
	],
	[
		`Who is Sorceror Prime?`,
		"Ancient One",
		"Dr Woo",
		"Dr Stefan Strange",
		"Wong",
		`Wong`,
	],
	[
		`Who was able to pick up Thor’s hammer in Endgame?`,
		"Iron Man",
		"Natasha Romanoff",
		"Rogers, Steve",
		"Thanos, The Mad Titan",
		`Rogers, Steve`,
	],

	[
		`What type of doctor is Dr Strange?`,
		"A Neurosurgeon",
		"Gynologist",
		"ENT",
		"General Surgeon",
		`A Neurosurgeon`,
	],
	[
		`Pepper Potts is allergic to what?`,
		"Strawberries",
		"Pumpkin",
		"Peanut",
		"Cherry",
		`Strawberries`,
	],
	[
		`On what planet was the Soul Stone in Infinity War?`,
		"Nowhere",
		"Vormir",
		"Neidavelier",
		"Niflheim",
		`Vormir`,
	],
	[
		`Scott Lang was trapped in the Quantum Realm for how long?`,
		"5 months",
		"5 hours",
		"5 mins",
		"5 years",
		`5 years`,
	],
	[
		` Where did Peggy tell Steve she wants to meet him for a dance?`,
		"LUX",
		"The Dancing CLub",
		"The Stork Club",
		"The Stoner Club",
		`The Stork Club`,
	],
	[
		`Thor played what video game in Avengers: Endgame?`,
		"PUBG",
		"Minecraft",
		"Fortnite",
		"Battle Field",
		`Fortnite`,
	],
	[
		`Nick Fury wears an eye patch over which eye?`,
		"His left eye",
		"His right eye",
		"Both eyes",
		"None",
		`His left eye`,
	],
	[
		` What is Tony Stark's daughter's name?`,
		"Maggie Stark",
		"Marriam Stark",
		"Morgan Stark",
		"Madhavi Stark",
		`Morgan Stark`,
	],
	[
		`What was victory feast of The Avengers?`,
		"Cheese Burger",
		"Donut",
		"Shahi Paneer",
		"Shahi Korma",
		`Shahi Korma`,
	],
];
